services:
  - type: web
    name: github-actions-runner
    env: docker
    buildCommand: ''
    startCommand: '/home/runner/start.sh'
    plan: free
    regions:
      - oregon
    dockerfilePath: ./Dockerfile
    branches:
      - main
    envVars:
      - key: RUNNER_TOKEN
        value: BKDJR2ATISNMLR5E2F2NIRTHJSBS4
