services:
  - type: web
    name: github-actions-runner
    env: docker
    buildCommand: ./start.sh
    startCommand: ./start.sh
    environment:
      - RUNNER_TOKEN=BKDJR2G3PI4LMZ2W3ML65ALHJRY3C
    port: 8080
    public: true
